trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Install python'

- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install selenium
  displayName: 'Install selenium'

- script: python3 google-serach-lambdatest.py
  displayName: 'Run tests'